# Sample YAML configuration file for VEBuild

# # PackageSources: Identifies directories with packages to build
#   - May be an absolute path to a directory containing (directories containing, recursively) DESCRIPTION files
#   - May be (1) relative to working directory
#   - If not found in working directory, then relative to VE_SOURCE
#   - VE_SOURCE defaults to VE_HOME/sources (for bootstrap from Git repository)
#   - VE_SOURCE may be set to another folder away from VE_HOME (e.g. if downloading a .zip for installation)
#   - Typically VE_SOURCE need not be set manually, since it will be set by the installer if needed

PackageSources:               # absolute path or relative to VE_SOURCE
  - framework                 # name of sub-directory of VE_SOURCE
  - modules
  - optional                  # name of sub-directory of VE_SOURCE
  # - external                # git-ignored folder within "sources" for VE packages originating elsewhere
  # - N:/Git-Repos/VisionEval-Extras
